version: "3"
services:
  mysql:
    image: 'mysql:8.0.31'
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=postcodesdb  
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      interval: 10s
      timeout: 5s
      retries: 5
  postcodes:
    image: 'harishreddy1232/postcodes:latest'
    container_name: postcodes
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=host.docker.internal  
    depends_on:
        mysql:
            condition: service_healthy
